services:
  - type: web
    name: research-rag-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: INDEX_NAME
        value: new-arxiv-papers
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PINECONE_API_KEY
        sync: false
      - key: HIVE_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false